### DISCUSSION TITLE
k8s schema validation error: could not find schema for Ingress

### DISCUSSION THREAD

**Discussion by rekibnikufesin** [datreeio/datree#141] [Q&A] [answered]
Hi,
I'm using datree version 0.7.1, kubectl version v1.21.2 to validate a schema (below). Getting an error `k8s schema validation error: could not find schema for Ingress`. Is this expected?

Yaml file:
```yaml
# Kibana HTTP Port
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: core-services
spec:
  rules:
    - http:
        paths:
          - path: /kibana
            pathType: Prefix
            backend:
              service:
                name: kibana
                port:
                  number: 5601
```
