### DISCUSSION TITLE
pre-commit config not working me, what am i missing? Thanks

### DISCUSSION THREAD

**Discussion by mannp** [datreeio/datree#838] [Q&A]
```
  - repo: https://github.com/datreeio/datree
    rev: 1.8.0
    hooks:
      - id: datree-docker
        name: datree test, run within docker
        description: Prevent Kubernetes misconfigurations from reaching production
        types: [file, yaml]
        language: docker_image
        pass_filenames: true
        args: [test, --ignore-missing-schemas, --only-k8s-files, --schema-version 1.24.6]
        entry: --user root datree/datree:latest
```
This results in the following error;
```
❯ git commit -m "--wip--"
yamllint....................................................................Passed
trim trailing whitespace....................................................Passed
fix end of files............................................................Passed
mixed line ending...........................................................Passed
CRLF end-lines remover......................................................Passed
Tabs remover................................................................Passed
Fix smartquote characters...................................................Passed
Check for unencrypted Kubernetes secrets in manifests.......................Passed
Detect hardcoded secrets....................................................Passed
datree test, run within docker..............................................Failed
- hook id: datree-docker
- exit code: 1

Error: unknown flag: --schema-version 1.24.6
```

I've tried various permutations and combinations of quotes around the flags, but none of them work, the same error results.

Can someone point me to my error please :)
