### DISCUSSION TITLE
Is it possible to skip rules for 1 container in a deployment that has many?

### DISCUSSION THREAD

**Discussion by timothystewart6** [datreeio/datree#939] [General]
e.g.

you have a deployment like so:

```yaml
      - name: cloudsql-proxy # we want to skip rules
        image: gcr.io/cloudsql-docker/gce-proxy:latest # 3rd party container
        imagePullPolicy: IfNotPresent
        # readinessProbe # 3rd party container that does not have a readinessProbe (only an example, they actually do)
      - name: some-other-container # we want to apply rules
        image: registry.example.com # 1st party container
        imagePullPolicy: Always
        readinessProbe: # 1st party container that does have a readinessProbe
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3
          timeoutSeconds: 3
          failureThreshold: 2
        command:
```

We would like to skip rules for the first container but not the second.  I don't think we can use annotations on the container (because they don't support them) and applying the skip rule to the deployment would then skip the rules for the item we need to check
