### ISSUE TITLE
inject the account token from the pre-commit config to the docker image

### ISSUE THREAD

**Issue by eyarz** [datreeio/datree#265]
**Is your feature request related to a problem? Please describe.**
when running Datree's pre-commit, there is no ("native") way to pass the account token to the docker image

**Describe the solution you'd like**
A way to inject the account token from the pre-commit config 

**Describe alternatives you've considered**
pass the account token as env variable to the docker image

**Comment by kevholmes** [comment]
Would you consider a PR to add in a `--token` flag to the CLI that accepts this parameter rather than an environment variable? Through this approach a user could configure their .pre-commit-config.yaml file like so:

```yaml
repos:
- repo: https://github.com/datreeio/datree
  rev: 0.14.49
  hooks:
  - id: datree-docker
    args: ['--token abcd123456789']
```

If you're open to that approach I could mock something up to quickly test if this solution will work with the existing [pre-commit-hooks.yaml](https://github.com/datreeio/datree/blob/main/.pre-commit-hooks.yaml) file and the existing args being passed in using the `docker_image` language type in pre-commit.
