### ISSUE TITLE
Show all possible errors during the `Kubernetes schema validation` step

### ISSUE THREAD

**Issue by eyarz** [datreeio/datree#350]
**Describe the bug**
When a file includes more than one K8s schema issues it's represented as one error (string) in the `Kubernetes schema validation` step

**To Reproduce**
1. Take the following config and run Datree against it:
```
apiVersion: v1
kind: pod
metaData:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
```
2. See the error: `k8s schema validation error: For field (root): Additional property metaData is not allowed - For field kind: kind must be one of the following: "Pod"`

**Expected behavior**
Two separated errors:
a. `For field kind: kind must be one of the following: "Pod"`
b. `For field (root): Additional property metaData is not allowed`

**Screenshots**
![image](https://user-images.githubusercontent.com/19731161/147571046-8045e916-d87d-4a57-8469-ba75592b6579.png)

**Desktop (please complete the following information):**
Not relevant.

**Datree version (run `datree version`):**
 - Version: 0.14.71

**Additional context**  
More info can be found [here](https://github.com/datreeio/datree/issues/116#issuecomment-1001624005).
