### ISSUE TITLE
Is it possible to skip rules on specific files?

### ISSUE THREAD

**Issue by exocode** [datreeio/datree#398]
**Is your feature request related to a problem? Please describe.**
I wanna have a slight more grained possibilty to apply checks only on specific files:

I have a `kind: job` manifest, which does not need the `readiness` or `liveness` probe check. But I don't like to skip that policy check for all of my other manifests (like `kind: deployment `)

**Is there a way to skip certain rules on certain files?**. Maybe it exists, but I didn't found it

**Describe the solution you'd like**

- a.) in the policies.yaml I am able to add files or rules which files to skip for certain policy check
- OR
- b.) An annotation can be added to the k8s manifest which checks should be skipped

a.) in policies.yml
```yaml
policies:
  - name: Default
    isDefault: true
    rules:
    - identifier: CONTAINERS_MISSING_LIVENESSPROBE_KEY
      messageOnFailure: Missing property object `livenessProbe` - add a properly configured livenessProbe to catch possible deadlocks
      skipped-files: 
        - ./**/kustomize/*-job.yaml # skips files or folders by regex
        - some/fiile.yml # skips a single specific file
 ```

b.) in manifest by annotations

```yaml
annotations: 
  datree.io.skip-policy-check: 
    - CONTAINERS_MISSING_READINESSPROBE_KEY
    - CONTAINERS_MISSING_LIVENESSPROBE_KEY
```
