### ISSUE TITLE
Skip rules by annotations

### ISSUE THREAD

**Issue by shmuelsa** [datreeio/datree#536]
**Is your feature request related to a problem? Please describe.**
As of now, we are unable to skip certain rules on specific files.

**Describe the solution you'd like**
In any manifest file, under metadata, we use a unique prefix annotation for skipping rule.
We will skip on checking certain rules in our policy check flow by extracting the unique skipped annotations 
from the manifest that contain the unique identifier rule as well as a custom message that explains why certain rules are skipped.

There will be two type of skipping:

- datree.io/[unique_rule_identifier]: “skip-message” - specific rule
- datree.io/skip-all-rules: “skip-message” - all rules

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-site
  namespace: test
  labels:
    owner: --
    environment: prod
    app: web
  **annotations:
    datree.io/skip-all-rules: “skip-message”
    datree.io/[unique_rule_identifier]: “message”**
```
