### ISSUE TITLE
Redundant built-in rule - HPA_MISSING_MAXREPLICAS_KEY

### ISSUE THREAD

**Issue by eyarz** [datreeio/datree#544]
**Is your feature request related to a problem? Please describe.**
The `Ensure HPA has maximum replicas configured` is redundant because this validation is happening during the schema validation step anyway.

**Describe the solution you'd like**
Remove/disable this built-in rule

**Additional context**
This YAML file
```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: store-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: store-autoscale
  minReplicas: 1
  metrics:
  - type: Object
    object:
      describedObject:
        kind: Service
        name: store-autoscale
      metric:
        name: "autoscaling.googleapis.com|gclb-capacity-utilization"
      target:
        averageValue: 70
        type: AverageValue
```
Will show this error when running `datree test`:
![image](https://user-images.githubusercontent.com/19731161/160894824-9ec3acb4-2def-461a-beb5-fb733316fa6f.png)

can be replaced with this rule:
https://github.com/datreeio/datree/issues/542
