### ISSUE TITLE
Argo workflow retrypolicy should not retry when error code = 1

### ISSUE THREAD

**Issue by nielstenboom** [datreeio/datree#723]
**Describe the bug**
There's a defaultrule that ensures that argo workflows only catches relevant errors ([code](https://github.com/datreeio/datree/blob/8915e9aacfd2f7e614382a7829ad9fccc53457e7/pkg/defaultRules/defaultRules.yaml#L1146-L1187)).

It specifically says to set the following expression in the retryPolicy of Argo Workflows:

```yaml
lastRetry.status == "Error" or (lastRetry.status == "Failed" and asInt(lastRetry.exitCode) not in [0])
```

But with this expression, it means that application exceptions resulting in a error code of 1 will always retry, and the retries will fail with the same error code.

Should the expression not be the following?:
```yaml
lastRetry.status == "Error" or (lastRetry.status == "Failed" and asInt(lastRetry.exitCode) not in [0,1])
```

Cheers!

**Comment by noaabarki** [comment]
Hey @nielstenboom! Nice to e-meet you. What an interesting question. 

This rule aims to ensure we don't miss any important errors and always retry if something has gone wrong, i.e exit code not 0. Check out [our docs](https://hub.datree.io/built-in-rules/ensure-workflow-retry-policy-catches-relevant-errors-only), we explained it in more detail. I'm a little bit confused with your suggestion, doesn't include `not in [0,1]` will cause retry to only when exist code is NOT 0 nor 1? I'm afraid this expression will miss failures.

Help me out here. Thank :)

**Comment by nielstenboom** [comment]
Hi @noaabarki, thank you for your swift response, nice to e-meet you as well! 

Let me attempt to explain what I mean with an example.

The docs on this mention the following:

"retryPolicy=Always is too much. The user only wants to retry on system-level errors (eg, the node dying or being preempted), **but not on errors occurring in user-level code since these failures indicate a bug**. In addition, this option is more suitable for long-running containers than workflows which are jobs."

The docs mention that you do no want to retry on errors occurring in user-level code. So say you have the following workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: scripts-python-
spec:
  entrypoint: python-script-example
  templates:
  - name: python-script-example
    steps:
    - - name: generate
        template: exception

  - name: exception
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        raise Exception("general exception")
```

This workflow will now be retried with the expression recommended by Datree because the exit code = 1, but these retries will all result in the same error. This should be the same with more complex user-code steps as well. Therefore I wondered if you should retry steps that failed with error code = 1?

**Comment by nielstenboom** [comment]
Another example to illustrate my point:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: scripts-python-
spec:
  entrypoint: python-script-example
  templates:
  - name: python-script-example
    steps:
    - - name: generate
        template: out-of-memory

  - name: out-of-memory
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        x = bytearray(1024*1024*1000*1000)
        print("if it reaches this print, it worked")
```

This script will simulate an OOM error, I've tested it and this actually fails with a 137 exit code. And an OOM error is something you DO want to retry as opposed to a user-code bug.

![image](https://user-images.githubusercontent.com/6594531/179476677-51ff08c5-48f9-47d5-995e-54aa838eb840.png)
