### ISSUE TITLE
Skip annotation not working on Jenkins CI/CD multi-container pod for readiness/liveness rules - is this a bug?

### ISSUE THREAD

**Issue by HariSekhon** [datreeio/datree#730]
**Describe the bug**

I'm getting  these error from `datree test`:

```
$ datree test jenkins-agent-pod.yaml

[X]  Ensure each container has a configured liveness probe  [17 occurrences]
    - metadata.name: N/A (kind: Pod)
[*]  Missing property object `livenessProbe` - add a properly configured livenessProbe to catch possible deadlocks

[X]  Ensure each container has a configured readiness probe  [17 occurrences]
    - metadata.name: N/A (kind: Pod)
[*]  Missing property object `readinessProbe` - add a properly configured readinessProbe to notify kubelet your Pods are ready for traffic
```

even though the file contains skip annotations:

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    datree.skip/CONTAINERS_MISSING_READINESSPROBE_KEY: readiness probe is not relevant for CI/CD CLI shell containers
    datree.skip/CONTAINERS_MISSING_LIVENESSPROBE_KEY: liveness probe is not relevant for CI/CD CLI shell containers
...
```

**To Reproduce**

```shell
wget https://raw.githubusercontent.com/HariSekhon/Kubernetes-configs/master/jenkins-agent-pod.yaml

datree test jenkins-agent-pod.yaml
```

**Expected behavior**

Expected it to show Skipped instead of failed with missing property errors.

**Desktop (please complete the following information):**
 - OS: Mac

**Datree version (run `datree version`):**
 - Version: 1.5.30

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: YAT7PdyxWVANePvsXQnPfK

**Comment by HariSekhon** [comment]
On a single container pod this same exactly copy and pasted annotation seems to work fine, so I wonder if it's related to the multiple containers in the pod above?

```shell
wget https://raw.githubusercontent.com/HariSekhon/Kubernetes-configs/master/pod.yaml

datree test pod.yaml
```

**Comment by adifayer** [comment]
@HariSekhon I was able to reproduce the exact same bug, I think that you're right- the name is missing only when there are multiple containers. We will take care of it within the next couple of days 🙏

**Comment by TzlilSwimmer123** [comment]
Hi @HariSekhon!
Thanks for letting us know

We are working on a fix at the moment. Meanwhile you can add the property `name` in the metadata of your pod and it should work until we will deploy the fix.
```
apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  name: jenkins
  labels:
    app: jenkins-agent
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    datree.skip/CONTAINERS_MISSING_READINESSPROBE_KEY: readiness probe is not relevant for CI/CD CLI shell containers
    datree.skip/CONTAINERS_MISSING_LIVENESSPROBE_KEY: liveness probe is not relevant for CI/CD CLI shell containers
...
```
Let me know if it didn't work
