### ISSUE TITLE
Exclude paths regex

### ISSUE THREAD

**Issue by HariSekhon** [datreeio/datree#732]
Feature Request to be able to define an exclude regex so that I can exclude problematic K8s patch files that Datree is tripping up on.

For an example of these patch yamls, you can see this run in my public Kubernetes repo:

https://github.com/HariSekhon/Kubernetes-configs/runs/7412852029?check_suite_focus=true

#### Proposed Solution

`--exclude` switch that can take a regex

Example usage:

```shell
$ datree test **/*.yaml --exclude '\.patch\.yaml$'
```

#### Describe alternatives you've considered

I do this in shell (via function in my [`.bash.d/kubernetes.sh`](https://github.com/HariSekhon/DevOps-Bash-tools/blob/master/.bash.d/kubernetes.sh)):

```shell
find . -type f -iname '*.y*ml' |
grep -v patch |
tr '\n' '\0' | 
xargs -0 datree test --only-k8s-files --ignore-missing-schemas
```

However, this doesn't work with [`action-datree`](https://github.com/datreeio/action-datree) so the CI/CD workflow is still broken.

I think it would be better handled via a native `--exclude` switch, but I'm open to other workarounds.

**Comment by adifayer** [comment]
@HariSekhon Did you try the --only-k8s-files flag? The idea of this flag is to skip validating all non-K8s files, that way you can avoid these failures. Let me know if it solves the problem :)

**Comment by HariSekhon** [comment]
Yes you can see it if you expand the action-datree call:

```
Run datreeio/action-datree@main
  with:
    path: **/*.y*ml
    cliArguments: --output simple --only-k8s-files --ignore-missing-schemas
    isHelmChart: false
    isKustomization: false
  env:
    DATREE_TOKEN: ***
```

so it was already there but did not solve this problem because these patch files have enough k8s structure to be picked up, but are missing other bits which they don't patch override - hence why I need a more explicit `--exclude` switch.

I mean, you guys could also debug all the failing patch files in my public repo and try to make datree smart enough to just deal with them, but whenever there is any unforeseen issue it might help to have a quick workaround like explicit `--exclude` regex.
