### ISSUE TITLE
improve CLI output when multiple object failed schema validation

### ISSUE THREAD

**Issue by eyarz** [datreeio/datree#759]
**Describe the bug**

**To Reproduce**
1. use the following manifest:
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rolebinding:app1-viewer
  namespace: demo-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role:viewer
subjects:
  - kind: ServiceAccount
    name: serviceaccount:app1
    namespace: demo-namespace
```
2. run the following command: `datree test -s 1.22.0 test.yaml`
3. read failed schema validation output

**Expected behavior**
The failure tip (`You can skip files with missing schemas instead of failing by using the --ignore-missing-schemas flag`) should be shown only once. It's unnecessary to show it for each object that failed the schema validation.

**Screenshots**
![image](https://user-images.githubusercontent.com/19731161/184817243-cea08967-79af-424e-b462-7d88048995b1.png)

**Additional context**  
If possible, include a YAML file to reproduce the bug.
