### ISSUE TITLE
datree pre-commit script and CRDs does not seem to behave as expected

### ISSUE THREAD

**Issue by fredleger** [datreeio/datree#811]
**Describe the bug**
Using pre-commit to validate a bunch of k8s manifests where there is some use of CRDs and can't make it to success without --ignore-missing-schemas

**To Reproduce**
0. Have (for example) a cert-manager ClusterIssuer in your k8s manifests
1. Extract missing CRDs with crd-extractor into local directory (same where your k8s manifests are)
2. Customize pre-commit hook (cf bellow)
3. Run command 'pre-commit run datree-docker --all-files'
5. See error

Config of PC hook:

```yaml
  - repo: https://github.com/datreeio/datree
    rev: 1.6.37
    hooks:
      - id: datree-docker
        args:
          - "test"
          - --no-record
          - --only-k8s-files
          - --schema-version=1.23.0
          - --schema-location='/src/.datree/crdSchemas/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json'
```
Error will be :

```
>>  File: /src/tools/3_letsencrypt-issuer.yaml

[V] YAML validation
[X] Kubernetes schema validation

❌  k8s schema validation error: could not find schema for ClusterIssuer
You can skip files with missing schemas instead of failing by using the `--ignore-missing-schemas` flag
```

**Expected behavior**

Running the same command inside the datree docker image does not present the same issue (cf screenshot)

**Screenshots**

<img width="1566" alt="image" src="https://user-images.githubusercontent.com/2778741/196374427-1c75bbba-947c-48bb-a311-f4236e7083aa.png">

<img width="1566" alt="image" src="https://user-images.githubusercontent.com/2778741/196375189-3bb41619-e8b9-4527-843b-5d45fd663693.png">

**Desktop (please complete the following information):**
 - OS: macos monterey / M1 silicon proc (aarm64)

**Datree version (run `datree version`):**
 - Version: 1.6.37 (from docker image actually)

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: None

**Additional context**  

Please feel free to ask more infos or tests
