### ISSUE TITLE
Skip rules for multiple resource

### ISSUE THREAD

**Issue by yellowhat** [datreeio/datree#819]
Hi,
I am looking for a way to skip a rule directly from the CLI or using a configuration file.

For example I am able to skip the following rule for a specific resource: 

```yaml
...
  annotations:
    datree.skip/DEPLOYMENT_INCORRECT_REPLICAS_VALUE: no need for multiple replicas.
...
```

I am not sure how to use [Policy-As-Code](https://hub.datree.io/setup/policy-as-code) to skip/disable rules.

**Datree version (run `datree version`):**
- 1.6.40

Thanks

**Comment by eyarz** [comment]
If you're using the **dashboard**, just turn the rule toggle off (under the `status` column):
<img width="916" alt="Screen Shot 2022-10-24 at 22 15 53" src="https://user-images.githubusercontent.com/19731161/197607359-6c141765-3881-4bc9-95da-4a3dbc8704f2.png">

If you're using **policy-as-code**, just delete/comment out the rule that you Datree to skip:
```yaml
apiVersion: v1
policies:
  - name: Default
    isDefault: true
    rules:
      - identifier: CONTAINERS_MISSING_IMAGE_VALUE_VERSION
        messageOnFailure: Incorrect value for key `image` - specify an image version to avoid unpleasant "version surprises" in the future
      # THIS RULE WILL BE IGNORED >>
      # - identifier: DEPLOYMENT_MISSING_LABEL_ENV_VALUE
      #   messageOnFailure: 'Missing label object `env` - add a proper environment description (e.g. "prod", "testing", etc.) to the Deployment config'

```
