### ISSUE TITLE
Datree does not recognize vpa UpdateMode = Off as string

### ISSUE THREAD

**Issue by itaydj** [datreeio/datree#820]
**Describe the bug**
We are trying to deploy a vpa resource from a helm chart we manage but even though we specify 'Off' as the value for 
updateMode, Datree check return the following error:

`k8s schema validation error: For field spec.updatePolicy.updateMode: Invalid type. Expected: string, given: boolean`

**To Reproduce**
1. deploy a vpa resource from a helm chart, use this vpa resource in the chart:
```yaml

{{- $fullName := include "project.fullname" . -}}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      maxAllowed:
        cpu: {{ .Values.vpa.maxAllowed.cpu }}
        memory: {{ .Values.vpa.maxAllowed.memory }}
      minAllowed:
        cpu: {{ .Values.vpa.minAllowed.cpu }}
        memory: {{ .Values.vpa.minAllowed.memory }}
  targetRef:
    apiVersion: apps/v1
    kind: {{- if .Values.statefulset.enabled }} statefulset {{ else }} deployment {{ end }}
    name: {{ $fullName }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode }}

```

use the following values.yaml file:
```yaml

vpa:
  updateMode: Off
  maxAllowed:
    cpu: 12
    memory: 25Gi
  minAllowed:
    cpu: 50m
    memory: 256Mi

```
3. run Datree against this chart:
```
helm datree test chart_ name 

```

**Expected behavior**
Datree will approve the resource with no issues

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Datree version (run `datree version`):**
 - Version: 1.5.30

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: 3cskkU34PXkAsYK9pV4M7T

**Comment by eyarz** [comment]
Hi @itaydj, this is not a bug, this is actually a real misconfiguration.
Unquoted `Off` is interpreted as a boolean by YAML:
* https://github.com/helm/helm/issues/5497
* https://github.com/kubernetes/autoscaler/issues/1455  

If you try to apply this config, it will be rejected by your cluster.
Just add quotes to [make it a string](https://cloud.google.com/kubernetes-engine/docs/concepts/verticalpodautoscaler#podupdatepolicy_v1_autoscalingk8sio) (`"Off"`), and you're all set :)

**Comment by itaydj** [comment]
Hi Eyar,
Thanks for the quick reply.
before I issued this issue I tried a few settings,
one of which was the following:

```yaml

  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}

```

while the values.yaml file is:

```yaml

vpa:
  updateMode: Off

```

This returns the following error:

```
[V] YAML validation
[X] Kubernetes schema validation
❌  k8s schema validation error: For field spec.updatePolicy.updateMode: spec.updatePolicy.updateMode must be one of the following: "Off", "Initial", "Recreate", "Auto"
[?] Policy check didn't run for this file
(Summary)
```

Hope this adds more information
and thanks again

**Comment by eyarz** [comment]
This is strange 🤔
Can you use the `helm template` command and check if the manifest is rendered with `Off` as a string?

**Comment by itaydj** [comment]
![off_yaml](https://user-images.githubusercontent.com/16012393/197766313-98a675fe-8514-4c45-a1f0-01699eb4ab6e.png)

it does...

**Comment by itaydj** [comment]
it does...
![off_yaml](https://user-images.githubusercontent.com/16012393/197766621-0f800c31-42b3-443a-846c-472562742cfb.png)

**Comment by eyarz** [comment]
What is your helm version? 
I used helm 3.8.2 & 3.10.1 (latest) to render the manifest, and this is what I got:
```yaml
...
  updatePolicy:
    updateMode: "false"
``` 

so when I use `updateMode: {{ .Values.vpa.updateMode | quote }}` (template) & `updateMode: Off` (values), datree returns the following error (which is correct!):
```
k8s schema validation error: For field spec.updatePolicy.updateMode: spec.updatePolicy.updateMode must be one of the following: "Off", "Initial", "Recreate", "Auto"
```
