### ISSUE TITLE
datree fails with yaml anchors on linux

### ISSUE THREAD

**Issue by pdeva** [datreeio/datree#884]
**Describe the bug**
using yaml anchors causes datree to fail on ubuntu 20. works on macos ventura tho.
we started noticing this issue in github-actions running on `ubuntu-latest` image, then were able to reproduce it on ubuntu desktop.

**To Reproduce**

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps

replacements:
- source: &datadog-version-source
    kind: Rollout
    name: auth
    namespace: astradot
    fieldPath: spec.template.spec.containers.[name=main].image
    options:
      delimiter: ':'
      index: 1
  targets: 
  - select: &datadog-version-target-select
      kind: Rollout
      name: auth
      namespace: astradot
    fieldPaths: &datadog-version-target-fieldpaths
    - metadata.labels.[tags.datadoghq.com/version]
    - spec.template.metadata.labels.[tags.datadoghq.com/version]

- source:
    <<: *datadog-version-source
    name: test-alb
  targets:
  - select: 
      <<: *datadog-version-target-select
      name: test-alb
    fieldPaths: *datadog-version-target-fieldpaths
        
```
 running datree:
```
datree kustomize test services --schema-version "1.24.0"

kustomize build errored: Error: invalid Kustomization: error converting YAML to JSON: yaml: unmarshal errors:
  line 26: key "name" already set in map
  line 30: key "name" already set in map
```
**Expected behavior**
work without error

**Screenshots**

**Desktop (please complete the following information):**
linux

**Datree version (run `datree version`):**
 - Version: 1.8.21

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: [e.g. C5fiX5Tm4SvxwkcfXVSHu5]

**Additional context**  
If possible, include a YAML file to reproduce the bug.
