### ISSUE TITLE
Fail to evaluate custom rule with Rego

### ISSUE THREAD

**Issue by flassagn** [datreeio/datree#910]
**Describe the bug**

Hi, I try to define custom rule with Rego. I never succeed to catch an error with Rego only with JSONSchema. 

**To Reproduce**

Here, the custom policy 

```yaml
apiVersion: v1
policies:
  - name: Starter
    isDefault: true
    rules:
      # - identifier: CUSTOM_WORKLOAD_INCORRECT_ENVIRONMENT_LABELS
      #   messageOnFailure: This message will override the rule's `defaultMessageOnFailure` property
      - identifier: CUSTOM_WORKLOAD_INCORRECT_ENVIRONMENT_LABELS_WITH_REGO
        messageOnFailure: This message will override the rule's `defaultMessageOnFailure` property
customRules:
  - identifier: CUSTOM_WORKLOAD_INCORRECT_ENVIRONMENT_LABELS
    name: Ensure correct environment labels are used [CUSTOM RULE]
    defaultMessageOnFailure: Use only approved environment labels (`prod`, `staging` and `test`)
    schema:
      properties:
        metadata:
          properties:
            labels:
              properties:
                environment:
                  enum:
                    - prod
                    - staging
                    - test
              required:
                - environment
          required:
            - labels
  - identifier: CUSTOM_WORKLOAD_INCORRECT_ENVIRONMENT_LABELS_WITH_REGO
    name: Ensure correct environment labels are used with Rego [CUSTOM RULE]
    defaultMessageOnFailure: Use only approved environment labels (`prod`, `staging` and `test`)
    schema:
      regoDefinition:
        code: |
          package examplePackage

          violation[labelExists] {
            provided := {label | input.metadata.labels[label]}
            required := {"prod","staging","test"}
            missing := required - provided
            labelExists := count(missing) > 0
          }
```
Here the input used to run the test 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/search: 'true'
  labels:
    app.kubernetes.io/instance: authorization-service-staging
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: authorization-server
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: authorization-server-0.1.0
  name: authorization-service-staging
  namespace: staging-env
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: authorization-service-staging
      app.kubernetes.io/name: authorization-server
  template:
    metadata:
      annotations:
        checksum/app-config: 1dd91440b228e7aa5e3ec3ddc511302f386be17e
        checksum/config: 79f0f89da207c177aade9af5a150f4ad9a65241422a9ce5de4bfcf218d61f749
        checksum/secret: 00408dce34226018f612fc7eb5414a5c621d9ad00f1ffdda20360d9cabeee086
        checksum/secret-kafka: 0a4c795df783fa74461fd516ecf926fc6b682734323c40766aa032a305c1be2b
      labels:
        app.kubernetes.io/instance: authorization-service-staging
        app.kubernetes.io/name: authorization-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: authorization-service-staging
                    app.kubernetes.io/name: authorization-server
                topologyKey: kubernetes.io/hostname
              weight: 10
      containers:
        - envFrom:
            - configMapRef:
                name: authorization-service-staging
            - configMapRef:
                name: authorization-service-staging-app
            - secretRef:
                name: authorization-service-staging-envsecret
          image: 'eu.gcr.io/staging-247808/authorization-server:staging-4916b7a39ca8'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /v1/oauth/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 3
          name: authorization-server
          ports:
            - containerPort: 3002
              name: http
            - containerPort: 3090
              name: monitoring
          readinessProbe:
            httpGet:
              path: /v1/oauth/ready
              port: http
            initialDelaySeconds: 8
            periodSeconds: 3
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 150Mi
          securityContext: {}
          volumeMounts:
            - mountPath: /kafka
              name: kafka-ssl
              readOnly: true
      nodeSelector:
        role: application
      securityContext: {}
      serviceAccountName: default
      volumes:
        - name: kafka-ssl
          secret:
            secretName: authorization-service-staging-kafka

```

**JSON Schema rule definition**

When I enable 

```yaml
  - name: Starter
    isDefault: true
    rules:
      - identifier: CUSTOM_WORKLOAD_INCORRECT_ENVIRONMENT_LABELS
        messageOnFailure: This message will override the rule's `defaultMessageOnFailure` property
      # - identifier: CUSTOM_WORKLOAD_INCORRECT_ENVIRONMENT_LABELS_WITH_REGO
      #   messageOnFailure: This message will override the rule's `defaultMessageOnFailure` property
```

I got 

```bash
❯ datree test tests/deployment.yaml --policy-config policies.yaml
>>  File: tests/deployment.yaml

[V] YAML validation
[V] Kubernetes schema validation

[X] Policy check

❌  Ensure correct environment labels are used [CUSTOM RULE]  [1 occurrence]
    - metadata.name: authorization-service-staging (kind: Deployment)
      > key: metadata.labels (line: 7:5)

💡  This message will override the rule's `defaultMessageOnFailure` property


(Summary)

- Passing YAML validation: 1/1

- Passing Kubernetes (1.24.8) schema validation: 1/1

- Passing policy check: 0/1

+-----------------------------------+-----------------------+
| Enabled rules in policy "Starter" | 1                     |
| Configs tested against policy     | 1                     |
| Total rules evaluated             | 1                     |
| Total rules skipped               | 0                     |
| Total rules failed                | 1                     |
| Total rules passed                | 0                     |
| See all rules in policy           | https://app.datree.io |
+-----------------------------------+-----------------------+
```

**Rego rule definition**

When I enable 

```yaml
  - name: Starter
    isDefault: true
    rules:
      # - identifier: CUSTOM_WORKLOAD_INCORRECT_ENVIRONMENT_LABELS
      #   messageOnFailure: This message will override the rule's `defaultMessageOnFailure` property
      - identifier: CUSTOM_WORKLOAD_INCORRECT_ENVIRONMENT_LABELS_WITH_REGO
        messageOnFailure: This message will override the rule's `defaultMessageOnFailure` property
```

I got 

```bash
❯ datree test tests/deployment.yaml --policy-config policies.yaml

(Summary)

- Passing YAML validation: 1/1

- Passing Kubernetes (1.24.8) schema validation: 1/1

- Passing policy check: 1/1

+-----------------------------------+-----------------------+
| Enabled rules in policy "Starter" | 1                     |
| Configs tested against policy     | 1                     |
| Total rules evaluated             | 1                     |
| Total rules skipped               | 0                     |
| Total rules failed                | 0                     |
| Total rules passed                | 1                     |
| See all rules in policy           | https://app.datree.io |
+-----------------------------------+-----------------------+
```

Note: I'm currently discovering the Rego language but I validated the definition with Playground. You could check at <https://play.openpolicyagent.org/p/Jyas8mw50E>

**Expected behavior**

I would like to have a consistent behavior between Rego and JSON schema rules definitions.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: EndeavourOS Linux

**Datree version (run `datree version`):**
 - Version: 1.8.21

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: cEvNSxpZKfekLKYrXY5zZh
