### ISSUE TITLE
CIS_INVALID_VALUE_SECCOMP_PROFILE Is reporting error when it should not

### ISSUE THREAD

**Issue by Socolin** [datreeio/datree#949]
Since today I'm getting errors on validation about `CIS_INVALID_VALUE_SECCOMP_PROFILE`  on resource kind that seems very weird:

- Service
- Ingress
- AzureIdentityBinding
- HorizontalPodAutoscaler 

I'm not sure I understand why it's required on those ?

**Comment by noorul** [comment]
Team, this is a blocker. I don't see a workaround also. It is surprising to see breaking behaviour without even a version change.

**Comment by noorul** [comment]
It is failing for this sample manifest
```yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sample-vpa
  namespace: gravity
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: sample
  updatePolicy:
    updateMode: Auto
```
