### ISSUE TITLE
[BUG] pre-commit hooks seems to ignore custom schema locations

### ISSUE THREAD

**Issue by fredleger** [datreeio/datree#973]
**Describe the bug**
When using pre-commit hooks i had bad time trying to add custom schema locations

**To Reproduce**
1. Setup the following commit hook config

```yaml
[...]
  - repo: https://github.com/datreeio/datree
    rev: 1.9.19
    hooks:
      - id: datree-system
        exclude: |
          (?x)^(
            ^\.github/.*|
            ^\.datree/.*|
            ^\.pre-commit-config.yaml
          )$
        args:
          - "test"
          - --no-record
          - --verbose
          - --schema-version=1.23.0
          - --schema-location='https://raw.githubusercontent.com/webofmars/CRDs-catalog/main/crds/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
[...]
```

2. run `pre-commit install`
3. run `pre-commit run -a datree-system` on a repo with a manifest not known by default to datree (for my case `ops.alexellis.io/clusterpullsecret/v1`)

![image](https://github.com/datreeio/datree/assets/2778741/f288ed56-4194-488d-b87f-9ad51097799a)

If i run the same command on pure command line (hence without pre-commit hook implied) :

![image](https://github.com/datreeio/datree/assets/2778741/89cb9ac8-a781-4ab8-a1a6-88cba07aabfa)

**Expected behavior**
schema locations should be easy to use with pre-commit hooks

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos (but i guess it's might be all)

**Datree version (run `datree version`):**
 - Version: 1.9.19

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: [e.g. ETJnw3X3cvv9JaTsEpjsMh]

**Additional context**  

Running in offline mode but i guess this is not an issue here
